### ISSUE TITLE
Add a placeholder attribute

### ISSUE THREAD

**Issue by aneurycasado** [arunghosh/react-pin-input#100]
Is there any reason why there is not a placeholder attribute that we can set?

**Comment by arunghosh** [comment]
@aneurycasado There is no particular reason. Didn't get any request to have one.

**Comment by aneurycasado** [comment]
@arunghosh Thank you for the quick reply! If possible, can you add a placeholder prop to <PinInput /> that would allow us to control the placeholder attributes on the input fields in <PinItem />

**Comment by arunghosh** [comment]
@aneurycasado You want placeholder for each input element?

**Comment by arunghosh** [comment]
@aneurycasado Can you provide an example for the placeholder you want to provide? I want to understand the use case better.

**Comment by ilgianfra** [comment]
I write here to not open a new bug (I hope it is ok)

To me it could be useful in order to make a  test on it, I am using react-testing-library and I didn't find any way to get the input and change the value.
Normally the input is queried with placeholder or aria-label

thanks!

**Comment by arunghosh** [comment]
@ilgianfra Placeholder and aria-label is available in **v.0.9.1**
