### ISSUE TITLE
Not all custom styles are applied

### ISSUE THREAD

**Issue by 20SangHun00** [arunghosh/react-pin-input#118]
So, I've installed today this module in my React-JS project, and I'm confronting now with an issue. Not all the styles written in `.pincode-input-text` and `.pincode-input-text:focus` classes are applied. In rest, everything's working awesome...

Here's the code snippet of these 2 classes
```
.pincode-input-text {
    text-align: center;
    color: #fff;
    border-color: #f5f5f5;
    background-color: #070713;
    width: 50px;
    height: 50px;

    font-size: 1rem;
    font-family: 'Roboto', sans-serif;
    line-height: 1.5;
  }

  .pincode-input-text:focus {
    border-color: #fff;
    outline: none;
    box-shadow: none;
  }
```

And here's a screen from my inspection tool:

![image](https://user-images.githubusercontent.com/35601730/68394994-85751400-0177-11ea-932c-369c7919aa18.png)

P.S. Yeah, I'm using SCSS, so I've done everything according to the pattern shown in `Readme.md`

**Comment by arunghosh** [comment]
@20SangHun00 There is a issue with the style implementation of the component. Need to check and fix it. A quick fix is to make the style `!important`.
