### ISSUE TITLE
Option to set initial value

### ISSUE THREAD

**Issue by sanjredfield** [arunghosh/react-pin-input#12]
Thank you for authoring and maintaining this component. 

One request: is it possible to add support for setting an initial PIN value? Right now, there is no straightforward way to set the values programmatically. Happy to submit a pull request, if this is something you are open to including.

**Comment by arunghosh** [comment]
@sanjredfield Happy to have to the pull request !!!

**Comment by Armanio** [comment]
@sanjredfield if you issue is actually set up your package version to 0.9.0 😉

**Comment by arunghosh** [comment]
Closed via pull request #60
