### ISSUE TITLE
Chrome autosave password is not disabled

### ISSUE THREAD

**Issue by Shruti776** [arunghosh/react-pin-input#147]
Autosave of pin entered in the boxes is enabled in the package.

Is there a way to disable the chrome autofill behavior if the PIN value is entered and submitted?

**Comment by arunghosh** [comment]
@Shruti776 Couldn't find a good solution to disable autosave. Did you mean to disable autocomplete?

**Comment by arunghosh** [comment]
@Shruti776 I couldn't find a good solution to find to disable autosave. Found some [hacks](https://stackoverflow.com/questions/41217019/how-to-prevent-a-browser-from-storing-password#answer-41343034)
