### ISSUE TITLE
Allow copy > paste

### ISSUE THREAD

**Issue by GazzaHazza** [arunghosh/react-pin-input#158]
Be great if could allow to copy and code then paste into first input and for the rest of the inputs fill with the correct number.

**Comment by arunghosh** [comment]
@GazzaHazza That sounds like a useful feature. I shall look into this.

**Comment by GazzaHazza** [comment]
That would be great, tbh i stole the idea from [react-code-input](https://github.com/40818419/react-code-input) 😄

**Comment by Jeanesily** [comment]
Looks like this is resolved here? https://github.com/arunghosh/react-pin-input/commit/59b7e457d3b9a62e12e120649aa55ec192f213d0#diff-b03452bcc2d823771542f5eba286e707ef5a5080ab3b9fd07215a6844d719d6b  (yay!)

**Comment by arunghosh** [comment]
@GazzaHazza Thank you for your help. The feature is already there. I apologize for not closing this issue.
