### ISSUE TITLE
Disable autocomplete password

### ISSUE THREAD

**Issue by nombrekeff** [arunghosh/react-pin-input#160]
Hey, is it possible to disable chrome's autocomplete password?

Any time I try writing in the pin item, it shows the dialog to fill in from passwords.

In plain HTML I tend to use `autoComplete="new-password"`, seems to do the job.

**Comment by nombrekeff** [comment]
I found a workaround: If I set focus, it does not show the dialog.

**Comment by arunghosh** [comment]
@nombrekeff  Thank you for the update. Sorry for the late response.
