### ISSUE TITLE
cant auto focus in fist row 

### ISSUE THREAD

**Issue by ilhamdoanggg** [arunghosh/react-pin-input#161]
in my component i use this, and its not auto focus for pointer 

please help 

![image](https://user-images.githubusercontent.com/9218660/87513621-35096b00-c6a3-11ea-962e-09304e9c9baa.png)

**Comment by arunghosh** [comment]
@ilhamdoanggg Sorry for the delay. Was busy with work. I will look into this issue.

**Comment by arunghosh** [comment]
@ilhamdoanggg Which browser are you using?

**Comment by ilhamdoanggg** [comment]
i using google chrome in PC and mobile @arunghosh

**Comment by ilhamdoanggg** [comment]
in this case
https://codesandbox.io/s/react-pin-input-forked-3oh1i

can you declare this.pin from state or props?

**Comment by ilhamdoanggg** [comment]
`ref={p => (this.pin = p)}`

**Comment by ilhamdoanggg** [comment]
`<PinInput length={4} ref={(n) => ele=n} />`
where ele from?

**Comment by arunghosh** [comment]
The auto focus is working. Can try accessing the codesandbox url directly - https://3oh1i.csb.app/ ?

I am not sure if I am answering the query. Else can you explain the issue?

**Comment by ilhamdoanggg** [comment]
this is my code

![image](https://user-images.githubusercontent.com/9218660/93025276-cacf6100-f626-11ea-9cb5-fb01c3ae81ea.png)

and its my result 

![image](https://user-images.githubusercontent.com/9218660/93025329-4c26f380-f627-11ea-9b07-0c8dd722817c.png)

and its for result console

![image](https://user-images.githubusercontent.com/9218660/93025341-64970e00-f627-11ea-95b4-93a276bf9c9d.png)

**Comment by ilhamdoanggg** [comment]
there is no pointer in first row
