### ISSUE TITLE
Browser Support

### ISSUE THREAD

**Issue by kevinhughes27** [arunghosh/react-pin-input#2]
I've been using this library in a project. I've been testing using Browserstack and I've run into issues on older browsers:

* The focus doesn't jump to the next input automatically 
* onComplete never fires

I've seen this so far on:
* iphone 6 running safari 8
* windows 7 running IE 11
* Nokia Lumia 930 running windows phone 8.1
* HTC One M8 android 4.4

I'll dig into this further myself and report back. If you've got an ideas let me know!

**Comment by kevinhughes27** [comment]
I've seen an exception come from this line: https://github.com/arunghosh/react-pin-input/blob/master/src/PinItem.jsx#L31

**Comment by kevinhughes27** [comment]
This could be the issue: https://caniuse.com/#search=isInteger

What do you think about re-writing that code to avoid this?

**Comment by arunghosh** [comment]
@kevinhughes27 Thank you for reporting. As you inferred, the issue seems to be because of the compatibility of **isInteger**. I can provide a fix by EOD(Indian Time) or if you can provide a pull-request I will be thankful :)

**Comment by arunghosh** [comment]
Closed via [commit](https://github.com/arunghosh/react-pin-input/commit/24751a9085e02120d40ec7199fb2101b3a8f3a32)

**Comment by kevinhughes27** [comment]
Thanks! 💖  I'll run through my tests again tonight!

**Comment by kevinhughes27** [comment]
Fixed all my tests! Thanks for fixing :rocket:
