### ISSUE TITLE
Unable to change or override default styles

### ISSUE THREAD

**Issue by muhammadtalha-13** [arunghosh/react-pin-input#4]
Hello.

Like the title says, I am unable to style the boxes. Overriding the default styles in a new .scss file does not work. Neither does the CSS in JSX method works. Even doing 'display: none' on the component has no effect whatsoever.

Kindly guide me on how to do it. Thank you.

**Comment by arunghosh** [comment]
@muhammadtalha-13 
In your css /scss file (make sure this file are added to your project) add

```
.pincode-input-container .pincode-input-text
{
   // Provide the style you want to override. 
   // Use !important if required.
} 
```
Inspect the element and see if the styles are being reflected.

**Comment by arunghosh** [comment]
@muhammadtalha-13 Did it work?

**Comment by muhammadtalha-13** [comment]
Yes it totally worked @arunghosh . Thank you for your immediate help. In the GitHub README and on the npmjs page, it was written like this:

.pincode-input-container
{
   .pincode-input-text
   {

   }
} 

Writing it like the way you said worked. Maybe change the info in the README and the npmjs page?

**Comment by arunghosh** [comment]
The README was referring to scss. But I think you are using css. I will make the required update.
