### ISSUE TITLE
No keypad showing in Android devices 

### ISSUE THREAD

**Issue by Olivr3** [arunghosh/react-pin-input#6]
![nokeypad](https://user-images.githubusercontent.com/20702895/34212034-dbff2fd4-e592-11e7-99a8-9a330c617b1e.png)
Hi 

I am not getting the keypad on the android devices if I set type="number". Please see image.

Cordova and ReactJS are used in this project that I am working on. 

```
<PinInput
    length={4}
    secret
    type="numeric"
    ref={p => pin = p}
    onComplete={(value) => {
      props.onComplete(value)
      pin.clear()
    }}
  />
```

thx in advance

**Comment by arunghosh** [comment]
@Olivr3  Can you give type="numeric"?

**Comment by Olivr3** [comment]
Hi @arunghosh 

I just did but it did not work.

**Comment by arunghosh** [comment]
@Olivr3 can you install latest version(_react-pin-input@0.5.2_) and give **type="number"** ?

**Comment by Olivr3** [comment]
@arunghosh sure thing!

**Comment by Olivr3** [comment]
It did not work. I am not getting the number pad.

https://stackoverflow.com/questions/19126856/make-input-type-password-use-number-pad-on-mobile-devices

**Comment by Olivr3** [comment]
Found the solution. 

Just style your ` input[type=tel]` with `...text-security`.

`.pincode-input-container input[type=tel] {
    -webkit-text-security: disc;
}`

`<PinInput
        length={4}
        type="numeric"
        focus
        ref={p => pin = p}
        onComplete={(value) => {
          props.onComplete(value)
          pin.clear()
        }}
      />`

This allows your inputs to be secret and have the number pad showing up on mobile devices.

**Comment by arunghosh** [comment]
@Olivr3 Cool. Also I have updated(react-pin-input@0.5.3) the support inputmode. So if you give type="numeric" it will set the inputmode as "numeric"
