### ISSUE TITLE
Expose events to API

### ISSUE THREAD

**Issue by hutber** [arunghosh/react-pin-input#9]
It would be great to be able to have access to methods through the api. I'd like to implement a custom keyboard for this.

**Comment by arunghosh** [comment]
@hutber can you provide more details on the method interface and the functionality?

**Comment by arunghosh** [comment]
Since no response. I am closing this issue.

**Comment by hutber** [comment]
Sorry, work was crazy when you asked. I'm happy for you to keep it closed. But what i was after was being able to create custom buttons and bind that keyboard to the pin component.
