### ISSUE TITLE
Add Disable prop

### ISSUE THREAD

**Issue by sayedsaeedhosseini** [arunghosh/react-pin-input#93]
Please add disable prop to toggling input's disabled attr.

**Comment by arunghosh** [comment]
@sayedsaeedhosseini Thank you for the suggestion.

I will check it during the weekend.

I am also happy to have pull requests for the same.

**Comment by sayedsaeedhosseini** [comment]
Thanks

**Comment by MikeBurke-Philips** [comment]
Would also like to kindly request this feature...  disable pin inputs after N attempts

**Comment by MikeBurke-Philips** [comment]
One way to do this through the pin ref

const els = pinRef.elements
                for (let i = 0; i < els.length; i++) {
                    els[i].input.disabled = "disabled"
                }

**Comment by arunghosh** [comment]
Added ```disabled``` property in ```v0.9.1```

**Comment by MikeBurke-Philips** [comment]
Thank you so much!
